spring:
  datasource:
    url: jdbc:mysql://120.25.206.164:3307/member?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
logging:
  config: classpath:logback-spring.xml


